{
 "title": "Home",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Estado Actual de todas las Estaciones",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_index),\n  CONCAT(CONCAT(entity_id,  ' => '), state) AS \"metric\",\n  geohash(location_centroid) AS geohash,\n  state,\n  CASE\n    WHEN state = 'DISPONIBLE' THEN 0.0\n    WHEN state = 'RESERVADO' THEN 5.0\n    WHEN state = 'LIBRE' THEN 10.0\n  END AS state_float\nFROM\n  \"doc\".\"etstation\"\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Histórico: Estaciones modificadas (por tiempo)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_index),\n  CONCAT(CONCAT(entity_id,  ' => '), state) AS \"metric\",\n  geohash(location_centroid) AS geohash,\n  state,\n  CASE\n    WHEN state = 'DISPONIBLE' THEN 0.0\n    WHEN state = 'RESERVADO' THEN 5.0\n    WHEN state = 'LIBRE' THEN 10.0\n  END AS state_float\nFROM\n  \"doc\".\"etstation\"\nWHERE\n  $__timeFilter(time_index)\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Estaciones disponibles (por tiempo)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_index),\n  CONCAT(CONCAT(entity_id,  ' => '), state) AS \"metric\",\n  geohash(location_centroid) AS geohash,\n  state,\n  CASE\n    WHEN state = 'DISPONIBLE' THEN 0.0\n    WHEN state = 'RESERVADO' THEN 5.0\n    WHEN state = 'LIBRE' THEN 10.0\n  END AS state_float\nFROM\n  \"doc\".\"etstation\"\nWHERE\n  $__timeFilter(time_index) AND\n  state = 'DISPONIBLE'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Estaciones reservadas (por tiempo)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_index),\n  CONCAT(CONCAT(entity_id,  ' => '), state) AS \"metric\",\n  geohash(location_centroid) AS geohash,\n  state,\n  CASE\n    WHEN state = 'DISPONIBLE' THEN 0.0\n    WHEN state = 'RESERVADO' THEN 5.0\n    WHEN state = 'LIBRE' THEN 10.0\n  END AS state_float\nFROM\n  \"doc\".\"etstation\"\nWHERE\n  $__timeFilter(time_index) AND\n  state = 'RESERVADO'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Estaciones libre (por tiempo)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_index),\n  CONCAT(CONCAT(entity_id,  ' => '), state) AS \"metric\",\n  geohash(location_centroid) AS geohash,\n  state,\n  CASE\n    WHEN state = 'DISPONIBLE' THEN 0.0\n    WHEN state = 'RESERVADO' THEN 5.0\n    WHEN state = 'LIBRE' THEN 10.0\n  END AS state_float\nFROM\n  \"doc\".\"etstation\"\nWHERE\n  $__timeFilter(time_index) AND\n  state = 'LIBRE'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Uso de bicis por usuario (por tiempo)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  entity_id,\n  count(state) AS \"state\"\nFROM etuser\nWHERE\n  $__timeFilter(time_index)\nGROUP BY entity_id\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Uso de bicis por categoría (por tiempo)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  category,\n  count(state) AS \"state\"\nFROM etbike\nGROUP BY category\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Top 5: Uso de estaciones (por tiempo)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  entity_id,\n  count(state) AS \"state\"\nFROM etstation\nWHERE\n  $__timeFilter(time_index)\nGROUP BY entity_id\nORDER BY 2 desc\nlimit 5"
    }
   ]
  },
  {
   "title": "Uso de bicis por usuario (por tiempo)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  entity_id,\n  count(state) AS \"state\"\nFROM etuser\nWHERE\n  $__timeFilter(time_index)\nGROUP BY entity_id\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Histórico: Uso de bicis por categoría desde el inicio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  category,\n  count(state) AS \"state\"\nFROM etbike\nGROUP BY category\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Top 5: Uso de estaciones (por tiempo)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  entity_id,\n  count(state) AS \"state\"\nFROM etstation\nGROUP BY entity_id\nORDER BY 2 desc\nLIMIT 5"
    }
   ]
  }
 ]
}